// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analyze/multiple": {
            "post": {
                "description": "Принимает несколько файлов в multipart/form-data, обрабатывает параллельно, возвращает массив результатов. Лимит: 10 файлов.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analysis"
                ],
                "summary": "Загрузить и проанализировать несколько файлов",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Файлы для анализа (до 10 штук)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Массив результатов анализа",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.AnalysisResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации (нет файлов или превышен лимит)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/analyze/upload": {
            "post": {
                "description": "Принимает multipart/form-data с файлом, отправляет в воркер-пул, возвращает результат анализа.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "analysis"
                ],
                "summary": "Загрузить и проанализировать один файл",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Файл для анализа (поддерживаются .txt, .md)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Результат анализа файла",
                        "schema": {
                            "$ref": "#/definitions/domain.AnalysisResult"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации (нет файла)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Возвращает статус OK, если сервис готов принимать запросы.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Проверка работоспособности сервиса",
                "responses": {
                    "200": {
                        "description": "Статус сервиса",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Raw metrics in Prometheus text format.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "monitoring"
                ],
                "summary": "Prometheus metrics endpoint",
                "responses": {
                    "200": {
                        "description": "Prometheus plain text"
                    },
                    "500": {
                        "description": "Metrics collection error"
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AnalysisResult": {
            "type": "object",
            "properties": {
                "avg-word-len": {
                    "type": "number"
                },
                "err": {},
                "file-path": {
                    "type": "string"
                },
                "lines": {
                    "type": "integer"
                },
                "longest-word": {
                    "$ref": "#/definitions/domain.Word"
                },
                "sentences": {
                    "type": "integer"
                },
                "symbols": {
                    "type": "integer"
                },
                "top-frequents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Word"
                    }
                },
                "words": {
                    "type": "integer"
                }
            }
        },
        "domain.Word": {
            "type": "object",
            "properties": {
                "length": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Text Analyzer API",
	Description:      "API для анализа текста и загрузки файлов.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
